name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mongo_dart: ^0.7.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  alfred: ^0.1.5+1
  

